name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Heroku
        run: |
          heroku config:set BOT_TOKEN=${{ secrets.BOT_TOKEN }} -a your-heroku-app-name
          git push https://heroku:$HEROKU_API_KEY@heroku.com/your-heroku-app-name.git HEAD:main
